name: React CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: build.zip
          path: build